--춘대학 실습문제 풀이

--1. 계열 정보를 저장할 카테고리 테이블을 만들려고 한다. 
CREATE TABLE TB_CATEGORY(
    NAME VARCHAR2(10),
    USE_YN CHAR(1) DEFAULT 'Y'
);

--2. 과목 구분을 저장할 테이블을 만들려고 한다.
CREATE TABLE TB_CLASS_TYPE(
    NO VARCHAR2(5),
    NAME VARCHAR2(10)
);

--3. TB_CATEGORY 테이블의 NAME컬럼에 PRIMARY KEY를 생성하시오
ALTER TABLE TB_CATEGORY ADD CONSTRAINT NAME_PK PRIMARY KEY(NAME);

--4. TB_CLASS_TYPE 테이블의 NAME칼럼에 NULL 값이 들어가지 않도록 속성 변경
ALTER TABLE TB_CLASS_TYPE MODIFY NAME NOT NULL;

--5. 두 테이블에서 칼럼 명이 NO인 것은 기존 타입을 유지하면서 크기는 10으로,
--컬럼명이 NAME인 것은 마찬가지로 기존 타입을 유지하면서 크기 20으로 변경하시오.
ALTER TABLE TB_CLASS_TYPE
MODIFY NO VARCHAR2(10)
MODIFY NAME VARCHAR2(20);

ALTER TABLE TB_CATEGORY
MODIFY NAME VARCHAR2(20);

--6. 두 테이블의 NO컬럼과 NAME컬럼의 이름을 각각 TB_를 제외한 테이블 이름이 앞에 붙은 형태로 변경
ALTER TABLE TB_CATEGORY
RENAME COLUMN TB_CATEGORY_NAME TO CATEGORY_NAME;

ALTER TABLE TB_CLASS_TYPE
RENAME COLUMN NAME TO CLASS_TYPE_NAME;

--7. TB_CATEGORY 테이블과 TB_CLASS_TYPE 테이블의 PRIMARY KEY 이름을 다음과 같이 변경하시오
-- PK_+ 칼럼이름
ALTER TABLE TB_CATEGORY
RENAME CONSTRAINT NAME_PK TO PK_CATEGORY_NAME;

--TB_CLASS_TYPE 테이블에 PK 추가 안해놨음. 추가해주자.
ALTER TABLE TB_CLASS_TYPE
ADD CONSTRAINT PK_NO PRIMARY KEY(NO);

--8. 다음과 같은 INSERT문을 수행한다.
INSERT INTO TB_CATEGORY VALUES('공학','Y');
INSERT INTO TB_CATEGORY VALUES('자연과학','Y');
INSERT INTO TB_CATEGORY VALUES('의학','Y');
INSERT INTO TB_CATEGORY VALUES('예체능','Y');
INSERT INTO TB_CATEGORY VALUES('인문사회','Y');
COMMIT;

--9. TB_DEPARTMENT의 CATEGORY컬럼이 TB_CATEGORY 테이블의 CATEGORY_NAME 컬럼을 부모값으로 참조하도록
--FOREIGN KEY 지정하시오. 이 때 KEY 이름은 KFI_테이블명_컬럼명.
ALTER TABLE TB_DEPARTMENT
ADD CONSTRAINT FK_DEPARTMENT_CATEGORY 
FOREIGN KEY(CATEGORY) REFERENCES TB_CATEGORY(CATEGORY_NAME);

