DROP TABLE MACARON_LIST;
DROP SEQUENCE SEQ_MACNO;

CREATE TABLE MACARON_LIST(
    MACARON_NO NUMBER NOT NULL,
    NAME VARCHAR(30) CONSTRAINT NAME_PK PRIMARY KEY,
    COLOUR VARCHAR(30) NOT NULL,
    FLAVOR VARCHAR(30) NOT NULL,
    BAKED_DATE DATE DEFAULT SYSDATE NOT NULL 
);

CREATE SEQUENCE SEQ_MACNO
START WITH 1
MAXVALUE 100
CYCLE;

INSERT INTO MACARON_LIST VALUES(SEQ_MACNO.NEXTVAL,'Å©¸²ºê·õ·¹','¿µ·ÕÇÑ °¥»ö','È¯»óÀÇ ¸À',DEFAULT);
INSERT INTO MACARON_LIST VALUES(SEQ_MACNO.NEXTVAL,'¹Ù´Ò¶ó','º£ÀÌÁö»ö','´Þ´Ù±¸¸®¿ìÀ¯¸À',DEFAULT);
INSERT INTO MACARON_LIST VALUES(SEQ_MACNO.NEXTVAL,'Á¦ÁÖÀ¯±â¸»Â÷','Ä§¿±¼ö±×¸°','½£ÀÇ´Ü³»À½¸À',DEFAULT);
INSERT INTO MACARON_LIST VALUES(SEQ_MACNO.NEXTVAL,'Á¦ÁÖ°¨±Ö','Â¸ÇÑ¿À·»Áö','½ÖÅ­±Ö¸À',DEFAULT);

COMMIT;
