
--춘대학 실습문제
--1.학과 이름과 계열을 표시하시오.
SELECT DEPARTMENT_NAME AS "학과 명",CATEGORY AS "계열" FROM TB_DEPARTMENT;

--2.학과의 학과 정원을 출력한다.
SELECT DEPARTMENT_NAME||'의 정원은 '||CAPACITY||'명 입니다.' AS "학과별 정원" FROM TB_DEPARTMENT;

--3. 국어국문학과 여학생 중 현재 휴학중인 여학생 찾기
SELECT STUDENT_NAME FROM TB_STUDENT WHERE STUDENT_SSN LIKE '_______2%' AND absence_yn = 'Y' AND DEPARTMENT_NO = '001';

--4. 도서관에서 대출 도서 장기연체자들을 찾아 이름 게시
SELECT STUDENT_NAME AS "장기연체자" 
FROM TB_STUDENT 
WHERE STUDENT_NO IN('A513079','A513090','A513091','A513110','A513119') 
ORDER BY STUDENT_NO DESC;

--5. 입학정원이 20명 이상 30명 이하인 학과들의 학과 이름과 계열을 출력하시오.
SELECT DEPARTMENT_NAME, CATEGORY, CAPACITY FROM TB_DEPARTMENT WHERE CAPACITY BETWEEN 20 AND 30;

--6. 춘 기술대학교 총장 이름을 알아낼 수 있는 SQL문장을 작성하라
SELECT PROFESSOR_NAME FROM TB_PROFESSOR WHERE DEPARTMENT_NO IS NULL;

--7. 전산상의 착오로 학과가 지정되어있지 않은 학생이 있는지 확인
SELECT STUDENT_NAME, DEPARTMENT_NO FROM TB_STUDENT WHERE DEPARTMENT_NO IS NOT NULL;

--8. 선수과목 존재하는 과목들은 어떤 과목들인지 과목번호 출력
SELECT CLASS_NO AS "선수과목있음" FROM TB_CLASS WHERE PREATTENDING_CLASS_NO IS NOT NULL;

--9. 춘 대학에는 어떤 계열들이 있는지 조회하기
SELECT DISTINCT CATEGORY FROM TB_DEPARTMENT ORDER BY CATEGORY;

--10. 02학번 전주 거주자들의 모임을 만드려고 한다. 휴학한 사람들은 제외한 재학중인 학생들의 학번, 이름, 주민번호를 출력하는 구문 작성
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN, STUDENT_ADDRESS FROM TB_STUDENT WHERE NOT ABSENCE_YN = 'Y' AND STUDENT_ADDRESS LIKE '%전주시%' AND ENTRANCE_DATE LIKE '02%';

